### ISSUE TITLE
应该支持SQL Server的TOP语句

### ISSUE THREAD

**Issue by sdcb** [TripleView/SqlParser.Net#3]
比如下面的代码：

```csharp
var sql = "SELECT TOP 100 * FROM [sys].[objects] ORDER BY [object_id] DESC";
var sqlAst = DbUtils.Parse(sql, SqlParser.Net.DbType.SqlServer);
```

会报错：
```
Message	An error occurred at position :17,near sql is:100 * FROM [sys].
InnerException	null
StackTrace	
   at SqlParser.Net.Ast.SqlParser.AcceptFourArithmeticOperationsBaseOperationUnit()
   at SqlParser.Net.Ast.SqlParser.AcceptBitwiseOperations()
   at SqlParser.Net.Ast.SqlParser.AcceptFourArithmeticOperationsMultiplyOrDivide()
   at SqlParser.Net.Ast.SqlParser.AcceptFourArithmeticOperationsAddOrSub()
   at SqlParser.Net.Ast.SqlParser.AcceptRelationalExpression()
   at SqlParser.Net.Ast.SqlParser.AcceptEquationOperationExpression()
   at SqlParser.Net.Ast.SqlParser.AcceptLogicalExpression()
   at SqlParser.Net.Ast.SqlParser.AcceptNestedComplexExpression()
   at SqlParser.Net.Ast.SqlParser.AcceptSelectItemsExpression()
   at SqlParser.Net.Ast.SqlParser.AcceptSelectQueryExpression()
   at SqlParser.Net.Ast.SqlParser.AcceptSelectExpression2()
   at SqlParser.Net.Ast.SqlParser.AcceptSelectExpression()
   at SqlParser.Net.Ast.SqlParser.Parse(List`1 tokens, String sql, DbType dbType)
   at SqlParser.Net.DbUtils.Parse(String sql, DbType dbType, Action`2 logger)
   at UserQuery.Main(), line 2
```

将TOP 100 *换成*之后，问题消失，说明它不支持SQL Server的SELECT TOP 100的功能。

**Comment by TripleView** [comment]
> 比如下面的代码：
> 
> ```cs
> var sql = "SELECT TOP 100 * FROM [sys].[objects] ORDER BY [object_id] DESC";
> var sqlAst = DbUtils.Parse(sql, SqlParser.Net.DbType.SqlServer);
> ```
> 
> 会报错：
> 
> ```
> Message	An error occurred at position :17,near sql is:100 * FROM [sys].
> InnerException	null
> StackTrace	
>    at SqlParser.Net.Ast.SqlParser.AcceptFourArithmeticOperationsBaseOperationUnit()
>    at SqlParser.Net.Ast.SqlParser.AcceptBitwiseOperations()
>    at SqlParser.Net.Ast.SqlParser.AcceptFourArithmeticOperationsMultiplyOrDivide()
>    at SqlParser.Net.Ast.SqlParser.AcceptFourArithmeticOperationsAddOrSub()
>    at SqlParser.Net.Ast.SqlParser.AcceptRelationalExpression()
>    at SqlParser.Net.Ast.SqlParser.AcceptEquationOperationExpression()
>    at SqlParser.Net.Ast.SqlParser.AcceptLogicalExpression()
>    at SqlParser.Net.Ast.SqlParser.AcceptNestedComplexExpression()
>    at SqlParser.Net.Ast.SqlParser.AcceptSelectItemsExpression()
>    at SqlParser.Net.Ast.SqlParser.AcceptSelectQueryExpression()
>    at SqlParser.Net.Ast.SqlParser.AcceptSelectExpression2()
>    at SqlParser.Net.Ast.SqlParser.AcceptSelectExpression()
>    at SqlParser.Net.Ast.SqlParser.Parse(List`1 tokens, String sql, DbType dbType)
>    at SqlParser.Net.DbUtils.Parse(String sql, DbType dbType, Action`2 logger)
>    at UserQuery.Main(), line 2
> ```
> 
> 将TOP 100 _换成_之后，问题消失，说明它不支持SQL Server的SELECT TOP 100的功能。

你好，现在确实没支持top 100这种语法，将会在稍后修复。

**Comment by TripleView** [comment]
你好，已修复，请将nuget包更新至1.0.1版本
